# Generated by Django 5.1.1 on 2024-10-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Дата оплаты"
            ),
        ),
    ]
